export const formErrors = {
    required: 'required',
    invalidGitRepoSlug: 'invalidGitRepoSlug',
    invalidGitRepoBranch: 'invalidGitRepoBranch',
    invalidGitRepoRemoteUrl: 'invalidGitRepoRemoteUrl',
    invalidExternalId: 'invalidExternalId',
    invalidFileName: 'invalidFileName',
    invalidBranchCondition: 'invalidBranchCondition',
    messageRequiresContentOrFiles: 'messageRequiresContentOrFiles',
    apiKeyExpiryMustBeFuture: 'apiKeyExpiryMustBeFuture',
    activeFlowsLimitMin: 'activeFlowsLimitMin',
    activeFlowsLimitMax: 'activeFlowsLimitMax',
    invalidAiProviderBaseUrl: 'invalidAiProviderBaseUrl',
    invalidAiProviderApiKeyHeader: 'invalidAiProviderApiKeyHeader',
} as const
